eureka:
  client:
    serviceUrl:
      defaultZone: http://test.eureka1.msh.com:18000/eureka/
spring:
  redis: #以下redis部分自行修改
    host: test.redis1.msh.com
    port: 6379
    #       password: dh35hebsd87ed9df9d0kemd9
    database: 0